name: ditonton
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  about:
    path: about
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.0.0
  get_it: ^7.1.3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  google_fonts: ^5.1.0
  http: ^1.0.0
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
dev_dependencies:
  mockito: ^5.0.8
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
    - certificates/
